### ISSUE TITLE
How to import custom Dreambooth model??

### ISSUE THREAD

**Issue by ajinkyabodke** [divamgupta/diffusionbee-stable-diffusion-ui#297]

**Comment by micksabox** [comment]
+1 would love to see this. From the Astria.ai service, I see I can export something called `ckpt`. Would be great if I can import this ckpt somehow and use it if that's how it would work.

**Comment by eAi** [comment]
Custom model support is coming

**Comment by divamgupta** [comment]
You can do that in the latest release.

**Comment by poornerd** [comment]
Super cool - but I can't figure out how to reference it.  I imported it, and selected it in the options instead of the default, but now how do I specifically use the text prompt to render the person in the model?

**Comment by poornerd** [comment]
Ok, that is where I trained mine, so I will try that...

**Comment by enzyme69** [comment]
I downloaded the latest DiffusionBee app for M1 machine, but not sure if I could see "import custom model" anywhere. I'll keep looking.

I tired strmr to train my old man face, it works pretty well with just 30 face photos. Would be nice if I could figure out how to "merge" multiple model trained. Because I end up with make .ckpt now, but if I use "sks man" from A, I am not sure how to have multiple person face.

What would be really interesting is the ability to mix 2 style. I mean img2img is kind of doing that sometimes.

**Comment by enzyme69** [comment]
Oh ok the latest app is here: (with custom model import)
https://github.com/divamgupta/diffusionbee-stable-diffusion-ui/releases/tag/1.5.1

The download link needs updating... :)
