### ISSUE TITLE
new update is not taken long promts

### ISSUE THREAD

**Issue by sebamacchia** [divamgupta/diffusionbee-stable-diffusion-ui#79]
when you use more than three lines, like about 70 words and you try to generate its basically does nothing

**Comment by tandefelt** [comment]
First, the update is absolutely amazing step further.. max 14 prompts etc.  Thank you majorly.. Divam.
Anyways: Glitch:
1) Yeps. Exactly same here, 4th line stops the program from working.. Yet.. I also noticed that..  the "process" circle flickered super super quickly, felt like a single fast frame, but saw it as an after image..  So, something is being attempted... likely quick fix.. (?).
2) Another feature which might be nice is that the overall text window could expand, if more than 3 lines of text is possible, so that scrolling is not needed etc.. makes things much easier.. maybe a divider/mouse expansion element like in Mac OS overall in finder menus etc.. 

Thank you again, Divam.. !

**Comment by tandefelt** [comment]
Update: The limit appears, again, not to be number of lines, at least in my end, but number of prompt characters: I tested the matter in my end with a character counter, 369 is still fine, 370 appears to break it :), hope this helps..

**Comment by christian314159** [comment]
Same happening here, but with less than 369 chars already. Haven't figured out a precise number yet.

**Comment by divamgupta** [comment]
Yes, it should display an error when prompt is too long now.

**Comment by murphy2712** [comment]
Is this normal, considering that v0.1 was working with long prompts?
